OPENAI_API_KEY =" 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"
OCR_API_KEY = "K87313976288957"
