OPENAI_API_KEY = "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"
OCR_API_KEY = "K87313976288957"
