OPENAI_API_KEY ="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"
OCR_API_KEY = "K87313976288957"
