OPENAI_API_KEY = "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"
OCR_API_KEY = "K87313976288957"
