OPENAI_API_KEY = "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"
OCR_API_KEY = "K87313976288957"
